# Generated by Django 4.2 on 2024-07-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover_image_book_pages_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='about_author',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
