# Generated by Django 4.2 on 2024-08-02 11:43

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_about_author_book_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='about_author',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='review',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
