# Generated by Django 4.2 on 2024-08-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_about_author_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('fiction', 'Fiction Books'), ('non-fiction', 'Non-Fiction Books'), ('children', "Children's Books")], max_length=100),
        ),
    ]
