# Generated by Django 4.2 on 2024-08-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('fiction', 'Fiction Books'), ('Non-Fiction', 'Non-Fiction Books'), ('children', "Children's Books")], max_length=100),
        ),
    ]
