# Generated by Django 4.2 on 2024-08-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('fiction', 'Fiction Books'), ('non-fiction', 'Non-Fiction Books'), ('children', "Children's Books")], max_length=100),
        ),
    ]
