# Generated by Django 4.2 on 2024-08-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
